#!/bin/bash
loadkeys de
boot="/dev/sdb1"
root="/dev/sdb2"

mkfs.fat $boot
mkfs.f2fs -f $root
mount $root /mnt
mkdir /mnt/boot
mount $boot /mnt/boot
pacstrap /mnt base linux linux-firmware nano sudo grub reflector
genfstab -U /mnt >> /mnt/etc/fstab

cp se /mnt/
arch-chroot /mnt
